from fpdf import FPDF

class MedicalReportPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'MEDICAL AI ASSISTANT (TAO SYSTEM)', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Tiered Agentic Oversight Framework', 0, 1, 'C')
        self.line(15, 30, 195, 30) # Kẻ đường line căn theo lề mới (15mm)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by AI (Review Required)', 0, 0, 'C')

def create_pdf_report(case_data, result_state):
    # 1. CẤU HÌNH TRANG: Tăng lề lên 15mm cho thoáng
    pdf = MedicalReportPDF(orientation='P', unit='mm', format='A4')
    pdf.set_margins(left=15, top=15, right=15)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20) # Margin đáy 20mm
    
    # Hàm xử lý text an toàn
    def safe_text(text):
        if not text: return "N/A"
        # Thay thế ký tự lạ, giữ lại nội dung đọc được nhất có thể
        return str(text).encode('latin-1', 'replace').decode('latin-1')

    # --- PHẦN 1: THÔNG TIN BỆNH NHÂN (Bố cục lại cho đỡ bị tràn) ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '1. PATIENT INFORMATION', 0, 1, 'L')
    
    # Case ID (Dòng riêng)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(25, 6, "Case ID:", 0, 0) # Nhãn rộng 25mm
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 6, safe_text(case_data.case_id), 0, 1) # Nội dung
    
    pdf.ln(2)

    # Symptoms (Dạng Block: Tiêu đề trên, nội dung dưới -> Tránh bị cắt chữ bên phải)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, "Symptoms:", 0, 1) # Xuống dòng luôn
    pdf.set_font('Arial', '', 10)
    # w=0 nghĩa là tự động mở rộng ra tận lề phải
    pdf.multi_cell(w=0, h=6, txt=safe_text(case_data.symptoms), border=0, align='L')
    
    pdf.ln(2)

    # Medical History (Dạng Block)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, "Medical History:", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(w=0, h=6, txt=safe_text(case_data.medical_history), border=0, align='L')
    
    pdf.ln(8)
    
    # --- PHẦN 2: KẾT LUẬN Y KHOA ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(240, 240, 240) # Màu xám nhạt hơn chút cho sang
    pdf.cell(0, 10, '  2. FINAL MEDICAL OPINION', 0, 1, 'L', fill=True)
    pdf.ln(4)
    
    if result_state.final_diagnosis:
        diag = result_state.final_diagnosis
        
        # Diagnosis
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(0, 6, "Diagnosis Summary:", 0, 1)
        pdf.set_font('Arial', '', 10)
        pdf.multi_cell(w=0, h=6, txt=safe_text(diag.diagnosis_summary))
        pdf.ln(3)
        
        # Treatment Plan
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(0, 6, "Treatment Plan / Recommendations:", 0, 1) 
        pdf.set_font('Arial', '', 10)
        pdf.multi_cell(w=0, h=6, txt=safe_text(diag.treatment_plan))
        pdf.ln(5)

        # Confidence & Agent (Chân trang phần này)
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(0, 6, f"Confidence Score: {diag.confidence_score * 100:.1f}%  |  Consultant: {safe_text(diag.agent_name)}", 0, 1, 'R')
    
    pdf.ln(8)
    
    # --- PHẦN 3: LẬP LUẬN LÂM SÀNG ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '3. CLINICAL REASONING', 0, 1, 'L')
    pdf.ln(2)
    
    pdf.set_font('Arial', '', 10)
    if result_state.final_diagnosis:
        pdf.multi_cell(w=0, h=6, txt=safe_text(result_state.final_diagnosis.reasoning))
    
    pdf.ln(10)
    
    # --- DISCLAIMER (Chữ đỏ) ---
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(180, 0, 0) # Đỏ đậm
    pdf.multi_cell(w=0, h=5, txt="DISCLAIMER: This report is generated by an Artificial Intelligence system (TAO Framework). It is intended for educational and informational purposes only and DOES NOT constitute professional medical advice, diagnosis, or treatment. Always seek the advice of your physician.")

    # Xuất file (Fix lỗi encode bytearray)
    output = pdf.output(dest='S')
    
    if isinstance(output, (bytes, bytearray)):
        return bytes(output)
    else:
        return output.encode('latin-1')